name: Update V2Ray Links

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت یکبار اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  update_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_v2ray_links.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add links.txt
          git commit -m "Auto update V2Ray links"
          git push
        continue-on-error: true
